name: camohm_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'

environment:
  sdk: ^3.11.5

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  camera: ^0.12.0+1
  path_provider: ^2.1.5
  image: ^4.8.0
  image_picker: ^1.2.1
  opencv_dart: ^2.2.1+4
  flutter_launcher_icons: ^0.14.4
  flex_color_picker: ^3.8.0
  logger: ^2.7.0
  permission_handler: ^12.0.1
  camera_ohm:
    path: ../../
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_test_ui: ^2.0.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
